[package]
name = "standard_stupid"
version = "0.1.0"
edition = "2021"

[dependencies]
errors_stupid = { path = "../errors_stupid/" }
tracing = { version = "0.1.38", default-features = false, features = [
  "log",
  "attributes",
  "valuable",
  "async-await",
] }
